# Docker Compose Stack mit InfluxDB und Grafana für das Projekt "Digitalisierung in der Energietechnik"
version: '3.6'
services:
  influxdb:
    container_name: influxdb-test
    image: influxdb:2.7.1-alpine
    ports:
      - '8086:8086' # InfluxDB wird am Server unter Port 8086 bereitgestellt.
    volumes:
      - influxdb-data:/var/lib/influxdb2 # Docker Volume: Hier werden die Daten permanent gespeichert.
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxpw # Sollte geaendert werden.
      - DOCKER_INFLUXDB_INIT_ORG=org-uni
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket-digitalisierung
      #- DOCKER_INFLUXDB_INIT_RETENTION=1w  # (optional) data retention: Wann werden Daten geloescht?
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8gs8r6ZZp@%EGnR@xRpJ@d4sH2M%5m8#  # (optional) admin-token definieren (sollte geaendert werden).
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana-testserver
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=gfuser
      - GF_SECURITY_ADMIN_PASSWORD=gfpw # Sollte geaendert werden.
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000' # Grafana wird am Server unter Port 3000 bereitgestellt.
    volumes:
      - grafana_data:/var/lib/grafana # Docker Volume: Hier werden die Daten permanent gespeichert.
      - ./config/grafana:/etc/grafana/provisioning/
      - ./config/grafana/dashboards/dashboard.json:/usr/share/grafana/public/dashboards/home.json

volumes: # Die Docker Volumes muessen hier definiert werden, werden dann automatisch mit dem Stack erstellt.
  grafana_data: {}
  influxdb-data: {}
